### ISSUE TITLE
Another question.

### ISSUE THREAD

**Issue by liudaizong** [Gorilla-Lab-SCUT/GeoA3#7] opened 2021-07-15 02:56 UTC
Hi, why almost all samples are predicted failed when I utilize the gen_data_mat.py? Any problem with the trained PointNet model?

**Comment by Yuxin-Wen** [comment] 2021-07-15 04:17
What data you used to train the model? I guess this is caused by the mismatch on the xyz-axis.

**Comment by liudaizong** [comment] 2021-07-15 04:24
> What data you used to train the model? I guess this is caused by the mismatch on the xyz-axis.

I utilize the model you provided in Pretrained file.

**Comment by Yuxin-Wen** [comment] 2021-07-15 04:34
Then what data you used in gen_data_mat.py?

**Comment by liudaizong** [comment] 2021-07-15 04:53
> Then what data you used in gen_data_mat.py?

I use the ModelNet40 testset.

**Comment by Yuxin-Wen** [comment] 2021-07-15 05:01
Download [here](https://shapenet.cs.stanford.edu/media/modelnet40_normal_resampled.zip)?

**Comment by liudaizong** [comment] 2021-07-15 05:01
> here

yes

**Comment by liudaizong** [comment] 2021-07-15 05:03
> Download [here](https://shapenet.cs.stanford.edu/media/modelnet40_normal_resampled.zip)?

Perhaps I need to train it from scratch again

**Comment by Yuxin-Wen** [comment] 2021-07-15 05:45
Strange, things go right in my environment. Could you provide more details about it?

![image](https://user-images.githubusercontent.com/58318379/125735217-45d81ae7-b090-43a1-b420-5400b86024e0.png)

**Comment by liudaizong** [comment] 2021-07-15 07:05
> Strange, things go right in my environment. Could you provide more details about it?
> 
> ![image](https://user-images.githubusercontent.com/58318379/125735217-45d81ae7-b090-43a1-b420-5400b86024e0.png)

It is very strange. I re-train the model and things go right. Perhaps the data is not matched with your provided model.

**Comment by liudaizong** [comment] 2021-07-15 08:26
I find the reason. Your class labels are different from the index order of ModeoNet40.

**Comment by Yuxin-Wen** [comment] 2021-07-15 09:32
The class labels we used are the ones as [gen_data_mat.py#L49](https://github.com/Gorilla-Lab-SCUT/GeoA3/blob/master/Provider/gen_data_mat.py#L49). If things go right, I'll close this issue. Feel free to reopen it if there is still problem.

**Closed by Yuxin-Wen** 2021-07-15 09:32 UTC

**Comment by HeBangYan** [comment] 2021-09-15 04:31
> I find the reason. Your class labels are different from the index order of ModeoNet40.

I also encountered the same problem, how did you solve it?

**Comment by liudaizong** [comment] 2021-09-15 08:17
> > I find the reason. Your class labels are different from the index order of ModeoNet40.
> 
> I also encountered the same problem, how did you solve it?

You can utilize the main_train.py file to train the model from scratch again.

**Comment by HeBangYan** [comment] 2021-09-16 03:07
> > > I find the reason. Your class labels are different from the index order of ModeoNet40.
> > 
> > 
> > I also encountered the same problem, how did you solve it?
> 
> You can utilize the main_train.py file to train the model from scratch again.

Thank you SO much ! 🙏
